### ISSUE TITLE
postfix won't build on 4.0.0-FC.01

### ISSUE THREAD

**Issue by dziq** [fearedbliss/bliss-overlay#5]
Hi Jonathan,
There is a problem with postfix and your kernel.
Unknown system type: Linux 4.0.0-FC.01. Build log below.
https://bpaste.net/show/7d196a58121d

**Comment by fearedbliss** [comment]
This isn't related to my kernel. I built and used this kernel before
releasing. It seems you are using funtoo patches for postfix.

I'll build postfix on gentoo to see if it builds. Also you shouldn't use my
4.0 kernel, it isnt keyworded and probably won't for a long time.

**Comment by fearedbliss** [comment]
This is the problem, for that version of postfix, the new 4.0 case hasn't
been added to postfix's makedefs.

Because of this, the following case gets hit:

*)   error "Unknown system type: $SYSTEM $RELEASE";;

This is line 523 of the postfix 2.11.3's makedefs:

/var/tmp/portage/mail-mta/postfix-2.11.3/work/postfix-2.11.3/makedefs (Only
available during compilation, you can also just extract the postfix source
files and inspect it)

Looking at postfix 3.0, 3.0.1, and postfix experimental 3.1-20150330, those
versions don't have this case either. So you will need to either patch it
yourself or wait for a newer version of postfix to be released.

-----------

This is the fix for this actually (Found at the Linux from Scratch postfix
page):

If you are running a linux-4.x kernel, apply the following sed to allow the
*makedefs* script to recognize it:

sed -i 's/Linux.3\*/Linux.[34]\*/' makedefs


http://www.linuxfromscratch.org/blfs/view/svn/server/postfix.html

We already have this in gentoo by the way:
/usr/portage/mail-mta/postfix/files/postfix-linux4.patch


On Mon, Apr 20, 2015 at 12:26 PM, Jonathan Vasquez <jvasquez1011@gmail.com>
wrote:

> This isn't related to my kernel. I built and used this kernel before
> releasing. It seems you are using funtoo patches for postfix.
>
> I'll build postfix on gentoo to see if it builds. Also you shouldn't use
> my 4.0 kernel, it isnt keyworded and probably won't for a long time.
> On Apr 20, 2015 12:14 PM, "Bartosz Nitkiewicz" <notifications@github.com>
> wrote:
>
>> Hi Jonathan,
>> There is a problem with postfix and your kernel.
>> Unknown system type: Linux 4.0.0-FC.01. Build log below.
>> https://bpaste.net/show/7d196a58121d
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fearedbliss/bliss-overlay/issues/5>.
>>
>


-- 
Jonathan Vasquez

**Comment by fearedbliss** [comment]
closing since this is not related to bliss-kernel.
